language: node_js

node_js:
  - node
  - 14
  - 12
  - 10

cache: yarn

before_script:
  - curl -fsSL https://deno.land/x/install/install.sh | sh -s v0.36.0
  - export PATH="/home/travis/.deno/bin:$PATH"
  - deno --version
